### ISSUE TITLE
PHP Parse Error

### ISSUE THREAD

**Issue by ittaskeu** [newerton/yii2-fancybox#13]
After composer update - FancyBoxAsset.php on row 19  syntax error, unexpected '.', expecting ']'

**Comment by newerton** [comment]
@ittaskeu What version of Yii and PHP do you use?

**Comment by ittaskeu** [comment]
yii 2.0.11
php 5.5.9

**Comment by halumein** [comment]
Concatenation will be valid with php 5.6.0+
here the declaration class properties article: 
http://php.net/manual/en/language.oop5.properties.php

It is time to upgrade.

**Comment by nikosid** [comment]
I also use php 5.5. Can we change this piece of code to working on 5.5?

**Comment by nikosid** [comment]
Merge it please https://github.com/newerton/yii2-fancybox/pull/14

**Comment by newerton** [comment]
@nikosid It conflicts with this issue.
https://github.com/newerton/yii2-fancybox/issues/6
