### ISSUE TITLE
fancy-mancy

### ISSUE THREAD

**Issue by mydesign** [newerton/yii2-fancybox#2]
newerton/fancybox
or
newerton/fancy-box ???

update composer or readme

**Comment by newerton** [comment]
What is the question?

Is correct the newerton/fancy-box.

https://github.com/newerton/fancy-box

**Comment by mydesign** [comment]
on clear installation, can't to install newerton/jquery-mousewheel
`php composer.phar require --prefer-dist newerton/yii2-fancybox "dev-master"`

for first it need to install newerton/fancy-box, then newerton/jquery-mousewheel, then newerton/yii2-fancybox...

**Comment by newerton** [comment]
Put your compose.json

You executed "composer update"?

**Comment by newerton** [comment]
@mydesign solved?
