### ISSUE TITLE
Js registration in FancyBoxAsset.php

### ISSUE THREAD

**Issue by germanliu** [newerton/yii2-fancybox#6]
Hi, why do you register the Js file using registerAssetFiles in FancyBoxAsset?

```
public function registerAssetFiles($view) {
        $this->js[] = 'jquery.fancybox' . (!YII_DEBUG ? '.pack' : '') . '.js';
        parent::registerAssetFiles($view);
    }
```

and not doing something like:

```
public $js = ['jquery.fancybox' . (!YII_DEBUG ? '.pack' : '') . '.js'];
```

The reason I ask is that using registerAssetFiles doesn't play well with Combining and Compressing Assets Using the asset Command (at the bottom of: http://www.yiiframework.com/doc-2.0/guide-structure-assets.html)

Thanks!

**Comment by vercotux** [comment]
This is indeed problematic. +1
